default: &default
  adapter: postgresql
  pool: 5
  username: secure_portal

development:
  <<: *default
  database: safehaven_development_anitha-mvp2

test:
  <<: *default
  database: secure_portal_test_anitha-mvp2

staging:
  <<: *default
  database: secure_portal_staging
  username: <%= ENV['SP_STAGING_DATABASE_U'] %>
  password: <%= ENV['SP_STAGING_DATABASE_P'] %>

production:
  <<: *default
  database: 'secure_portal_production'
  username: <%= ENV['SP_PROD_DATABASE_U'] %>
  password: <%= ENV['SP_PROD_DATABASE_P'] %>
